# Tests using networkx and the status game

Jan 2025

In [18]:
import mesa
import numpy as np
from mesa.datacollection import DataCollector
from scipy import stats
import math
import networkx as nx
import random

In [19]:
g = nx.Graph()
agents_list = np.arange(0,200).tolist()

In [20]:
random.shuffle(agents_list)

pairs = []
for i in range(0, len(agents_list), 2):
    a1 = agents_list[i]
    a2 = agents_list[i+1]
    pairs.append((a1, a2))

# Add them to the network
g.add_edges_from(pairs) # For now, this is an undirected / unweighted graph

In [23]:
pairs

[(35, 60),
 (88, 130),
 (111, 74),
 (41, 22),
 (149, 19),
 (10, 36),
 (165, 160),
 (140, 153),
 (148, 145),
 (93, 141),
 (131, 161),
 (163, 71),
 (40, 177),
 (101, 162),
 (110, 99),
 (186, 84),
 (56, 92),
 (66, 170),
 (172, 65),
 (138, 183),
 (159, 90),
 (45, 122),
 (87, 24),
 (81, 112),
 (3, 47),
 (54, 37),
 (173, 121),
 (133, 134),
 (95, 196),
 (76, 198),
 (127, 51),
 (181, 150),
 (25, 152),
 (49, 53),
 (57, 104),
 (12, 136),
 (103, 96),
 (187, 50),
 (135, 195),
 (171, 13),
 (1, 175),
 (39, 190),
 (192, 64),
 (146, 194),
 (109, 193),
 (124, 191),
 (63, 14),
 (83, 137),
 (85, 199),
 (23, 4),
 (126, 197),
 (97, 26),
 (58, 77),
 (8, 62),
 (107, 168),
 (0, 180),
 (86, 38),
 (11, 94),
 (67, 16),
 (157, 132),
 (105, 102),
 (9, 116),
 (167, 69),
 (30, 155),
 (7, 72),
 (46, 114),
 (147, 128),
 (185, 118),
 (174, 189),
 (18, 55),
 (32, 119),
 (129, 106),
 (166, 27),
 (34, 144),
 (115, 169),
 (78, 143),
 (182, 125),
 (28, 80),
 (188, 21),
 (20, 59),
 (2, 42),
 (184, 48),
 (6, 142),
 (123, 120)

In [35]:
g.nodes[35]["status"] = 1
g.nodes[35]["s"] = [12,4254,6,36,35,631]

In [36]:
g.nodes[35]

{'status': 1, 's': [12, 4254, 6, 36, 35, 631]}

In [37]:
import networkx as nx

G = nx.Graph()

# Add nodes with attributes
G.add_node('A', role='origin')
G.add_node('B', attr='some_value_for_B')
G.add_node('C', attr='some_value_for_C')

# Add edges
G.add_edge('A', 'B')
G.add_edge('A', 'C')

# From node "A", iterate over neighbors and get a node attribute
for neighbor in G.neighbors('A'):
    # Access the 'attr' attribute of the neighbor
    attr_value = G.nodes[neighbor].get('attr', None)
    print(f"Neighbor {neighbor} has 'attr' = {attr_value}")


Neighbor B has 'attr' = some_value_for_B
Neighbor C has 'attr' = some_value_for_C


In [42]:
[G.nodes[n]['attr'] for n in G.neighbors('A')]

['some_value_for_B', 'some_value_for_C']

In [ ]:
np.percentile(np.arange(1,10000000), [0,3,5,7,8,1])

array([200000.96, 300000.94, 500000.9 , 700000.86, 800000.84, 100000.98])

In [88]:
cons = [11,4,6,8,12,4436,7,88,43,21,18,3,45,67,4,20,1]
np.percentile(cons, 50)

12.0

In [90]:
100 - stats.percentileofscore(np.abs(np.array(cons)-12), np.abs(np.array(cons)-12))

array([88.23529412, 52.94117647, 67.64705882, 82.35294118, 94.11764706,
        0.        , 76.47058824,  5.88235294, 23.52941176, 38.23529412,
       67.64705882, 38.23529412, 17.64705882, 11.76470588, 52.94117647,
       52.94117647, 29.41176471])

In [72]:
np.arange(1,100)-50

array([-49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39, -38, -37,
       -36, -35, -34, -33, -32, -31, -30, -29, -28, -27, -26, -25, -24,
       -23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13, -12, -11,
       -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,
        16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
        29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
        42,  43,  44,  45,  46,  47,  48,  49])

In [91]:
max([1,2,45,61])

61